### ISSUE TITLE
关于 token 过期处理？

### ISSUE THREAD

**Issue by pihc** [Qsnh/CloudBookMark#1]
请教您一个问题：
我现在也是用 iview 搭建的一个后台 在 AuthServiceProvider 中设置了 access_token 的过期时间
```
public function boot()
    {
       // Passport 的路由
        Passport::routes();
        // access_token 过期时间
        Passport::tokensExpireIn(Carbon::now()->addMinutes(30));
        // refreshTokens 过期时间
        Passport::refreshTokensExpireIn(Carbon::now()->addDays(10));
    }
```
我想知道 access_token 过期后，去刷新 token 怎么处理
1. 如何判断 access_token 过期？ 我这里是在每个响应 catch 中，判断 status == 401 然后去调用 token/refresh，有时候会出现不停的去 调用 token/refresh，挺头疼的
2. refresh_token 过期后退出登录怎么处理？

😄 如果您能看到的话，可否解惑一下，新手 第一次用 laravel and vuejs :sob:

**Comment by Qsnh** [comment]
前端请求 token 的时候已经返回了 token 的有效时间，具体看返回字段。主要是根据有效时间判断是否可以继续刷新，不可以就直接退出，可以就刷新。无法刷新可根据HTTP状态码进行判断。
