### ISSUE TITLE
为什么我用GuzzleHttp\Client  post一直不成功

### ISSUE THREAD

**Issue by huaiguoguo** [Qsnh/CloudBookMark#2]
我用的是laravel 5.6
GuzzleHttp\Client 版本是：6.2

![image](https://user-images.githubusercontent.com/1888094/38357080-2feec15e-38f4-11e8-91ed-98937d4bb631.png)

![image](https://user-images.githubusercontent.com/1888094/38357062-200eddf0-38f4-11e8-8945-8416f9c7ffdd.png)

![image](https://user-images.githubusercontent.com/1888094/38357105-3c113cd2-38f4-11e8-8721-7ab8de2ff550.png)

但是我用postmain  去请求 http://xxx.com/oauth/token是成功的

![image](https://user-images.githubusercontent.com/1888094/38357763-119bb494-38f6-11e8-8139-5a6eef72e1cf.png)

**Comment by Qsnh** [comment]
因为你是本地开发的，nginx进程都是通过本地端口9000请求的，本地请求本地的会导致阻塞的
